In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
# 计算y关于x的梯度之前，我们需要一个地方来存储梯度。
x.requires_grad_(True)
x.grad

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
# 通过调用反向传播函数来自动计算y关于x每个分量的梯度。
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
x.grad == 4 * x

tensor([True, True, True, True])

In [6]:
# 在默认情况下， PyTorch会累积梯度，我们需要清除之前的值。
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [8]:
# 深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和。
# 对非标量调用`backward`需要传入一个‘gradient’参数。
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [9]:
# 将某些计算移动到记录的计算图之外
x.grad.zero_()
y = x * x
# 把y当作一个常数
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [12]:
# 使用python控制流构建函数的计算图，我们仍然可以计算得到的变量的梯度。
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d/a

tensor(True)